const toolPath = (slug: string) => `/tool/${slug}` as const;

export const routes = {
  MULTIFAMILY_DEVELOPMENT: toolPath("multifamily-development"),
  INDUSTRIAL_DEVELOPMENT: toolPath("industrial-development"),
  COMMERCIAL_DEVELOPMENT: toolPath("commercial-development"),
  RESIDENTIAL_DEVELOPMENT: toolPath("residential-development"),
  MULTI_FAMILY_PRICE_PER_DOOR: toolPath("multifamily-price-calculator"),
  HOTEL_PRICE_PER_KEY: toolPath("hotel-price-calculator"),
  INDUSTRIAL_PRICE_PER_SQFT: toolPath("industrial-price-per-sqft-calculator"),
  MULTIFAMILY_ANALYSIS: toolPath("multifamily-analysis"),
  INDUSTRIAL_PROFORMA: toolPath("industrial-commercial-proforma"),
  HOW_TO_LAND_FOR_MULTIFAMILY: "/how-to-analyzis-land-for-multifamily",
  IRR_CALCULATOR: toolPath("irr-calculator"),
  HARD_MONEY_COST_ESTIMATOR: toolPath("hard-money-calculator"),
  WATERFALL: toolPath("waterfall-generator"),
  CONSTRUCTION_BUDGET: toolPath("construction-budget-generator"),
  SITE_PLAN_BUILDER: toolPath("site-plan-builder"),
  CUT_FILL_CALCULATOR: toolPath("cut-fill-calculator"),
  TOPOLOGY_ANALYSIS: toolPath("topology-analysis"),
  SUBDIVISION_GENERATOR: toolPath("subdivision-generator"),
  HOUSE_FLIPPING_CALCULATOR: toolPath("house-flipping-calculator"),
  CONSTRUCTION_LOAN_CALCULATOR: toolPath("construction-loan-calculator"),
  HOME_MORTGAGE_CALCULATOR: toolPath("home-mortgage-calculator"),
  LEASE_EXPIRY_SCHEDULE: toolPath("lease-expiry-schedule"),
  TOOLS: "/tools",
  HOME: "/",

  // Authentication & User-related Routes
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  REGISTER: "/register",

  // General Pages
  LANDING_PAGE: "/landing",
  END_FREE_TRIAL: "/end-free-trial",
  PAYMENT: "/payment",
  COMPLETION: "/completion",
  SIGN_UP: "/sign-up",
  TERMS: "/terms",
} as const;

export const LEGACY_TOOL_REDIRECTS: Record<string, string> = {
  "/multifamily-development": routes.MULTIFAMILY_DEVELOPMENT,
  "/industrial-development": routes.INDUSTRIAL_DEVELOPMENT,
  "/commercial-development": routes.COMMERCIAL_DEVELOPMENT,
  "/residential-development": routes.RESIDENTIAL_DEVELOPMENT,
  "/multifamily-price-calculator": routes.MULTI_FAMILY_PRICE_PER_DOOR,
  "/hotel-price-calculator": routes.HOTEL_PRICE_PER_KEY,
  "/industrial-price-per-sqft-calculator": routes.INDUSTRIAL_PRICE_PER_SQFT,
  "/multifamily-analysis": routes.MULTIFAMILY_ANALYSIS,
  "/industrial-commercial-proforma": routes.INDUSTRIAL_PROFORMA,
  "/irr-calculator": routes.IRR_CALCULATOR,
  "/hard-money-calculator": routes.HARD_MONEY_COST_ESTIMATOR,
  "/waterfall-generator": routes.WATERFALL,
  "/construction-budget-generator": routes.CONSTRUCTION_BUDGET,
  "/site-plan-builder": routes.SITE_PLAN_BUILDER,
  "/cut-fill-calculator": routes.CUT_FILL_CALCULATOR,
  "/topology-analysis": routes.TOPOLOGY_ANALYSIS,
  "/subdivision-generator": routes.SUBDIVISION_GENERATOR,
  "/house-flipping-calculator": routes.HOUSE_FLIPPING_CALCULATOR,
  "/construction-loan-calculator": routes.CONSTRUCTION_LOAN_CALCULATOR,
  "/home-mortgage-calculator": routes.HOME_MORTGAGE_CALCULATOR,
  "/lease-expiry-schedule": routes.LEASE_EXPIRY_SCHEDULE,
};
