import { EAllStates, EPageNames } from "./types";

export const SQ_FT_PER_ACRE = 43560;
export const infrastructurePercentage = 70;

export const DEFAULT_VALUES = {
    [EPageNames.RESIDENTIAL_DEVELOPMENT]: {
        grossAcres: 1.65,
        unbuildableAcres: 0,
        sqFtPerLot: 1500,
        unitsPerAcre: 0,
        houseSize: 1500,
        housePricePerSqFt: 300,
        hardCostPerSqFt: 185,
        permits: 12000,
        miscCosts: 7500,
        homeBuilderProfitPercentage: 20,
        realEstateCommissionPercentage: 3,
        landDeveloperProfitPercentage: 15,
        costToDevelopPerLot: 40000,
        ownedLandCost: 0,
        // NOT USED ON THIS PAGE
        builderProfitPercentage: 0,
        buildingPricePerSqFt: 0,
        catchAll: 0,
        commonSpacePercentage: 0,
        costToDevelop: 0,
        costToDevelopPerUnit: 0,
        maxImperviousSurfaceRatio: 0,
        multifamilyPricePerSqFt: 0,
        numberOfFloors: 0,
        numberOfUnits: 0,
        parkingRatio: 0,
        parkingSpotsPerUnit: 0,
        requiresHandicappedParking: true,
        SDCFees: 0,

    },
    [EPageNames.MULTIFAMILY_DEVELOPMENT]: {
        grossAcres: 0.25,
        unbuildableAcres: 0,
        numberOfUnits: 4,
        numberOfFloors: 2,
        maxImperviousSurfaceRatio: 60,
        commonSpacePercentage: 0,
        parkingSpotsPerUnit: 1.5,
        requiresHandicappedParking: true,
        catchAll: 1.8,
        multifamilyPricePerSqFt: 300,
        hardCostPerSqFt: 185,
        permits: 12000,
        miscCosts: 7500,
        builderProfitPercentage: 20,
        realEstateCommissionPercentage: 3,
        landDeveloperProfitPercentage: 15,
        costToDevelopPerUnit: 40000,
        ownedLandCost: 0,
        // NOT USED ON THIS PAGE       
        buildingPricePerSqFt: 0,
        costToDevelop: 0,
        costToDevelopPerLot: 0,
        homeBuilderProfitPercentage: 0,
        housePricePerSqFt: 0,
        houseSize: 0,
        parkingRatio: 0,
        SDCFees: 0,
        sqFtPerLot: 0,
        unitsPerAcre: 0,
    },
    [EPageNames.INDUSTRIAL_DEVELOPMENT]: {
        grossAcres: 0.3,
        unbuildableAcres: 0,
        numberOfFloors: 2,
        maxImperviousSurfaceRatio: 60,
        commonSpacePercentage: 40,
        parkingRatio: 2,
        catchAll: 1.8,
        buildingPricePerSqFt: 300,
        hardCostPerSqFt: 185,
        permits: 12000,
        miscCosts: 7500,
        homeBuilderProfitPercentage: 20,
        realEstateCommissionPercentage: 3,
        landDeveloperProfitPercentage: 15,
        costToDevelop: 40000,
        SDCFees: 20000,
        ownedLandCost: 0,
        // NOT USED ON THIS PAGE
        builderProfitPercentage: 0,
        costToDevelopPerLot: 0,
        costToDevelopPerUnit: 0,
        housePricePerSqFt: 0,
        houseSize: 0,
        multifamilyPricePerSqFt: 0,
        numberOfUnits: 0,
        parkingSpotsPerUnit: 0,
        requiresHandicappedParking: true,
        sqFtPerLot: 0,
        unitsPerAcre: 0,
    }
}



export const allStateVariables = [
    EAllStates.builderProfitPercentage,
    EAllStates.buildingPricePerSqFt,
    EAllStates.catchAll,
    EAllStates.commonSpacePercentage,
    EAllStates.costToDevelop,
    EAllStates.costToDevelopPerLot,
    EAllStates.costToDevelopPerUnit,
    EAllStates.grossAcres,
    EAllStates.hardCostPerSqFt,
    EAllStates.homeBuilderProfitPercentage,
    EAllStates.housePricePerSqFt,
    EAllStates.houseSize,
    EAllStates.landDeveloperProfitPercentage,
    EAllStates.maxImperviousSurfaceRatio,
    EAllStates.miscCosts,
    EAllStates.multifamilyPricePerSqFt,
    EAllStates.numberOfFloors,
    EAllStates.numberOfUnits,
    EAllStates.ownedLandCost,
    EAllStates.parkingRatio,
    EAllStates.parkingSpotsPerUnit,
    EAllStates.permits,
    EAllStates.realEstateCommissionPercentage,
    EAllStates.requiresHandicappedParking,
    EAllStates.SDCFees,
    EAllStates.sqFtPerLot,
    EAllStates.unbuildableAcres,
    EAllStates.unitsPerAcre,
]