import { EAllStates, EPageNames } from "./types";

export const SQ_FT_PER_ACRE = 43560;
export const infrastructurePercentage = 70;

export const DEFAULT_VALUES_ZEROS = {
    grossAcres: "0",
    unbuildableAcres: "0",
    numberOfFloors: "0",
    maxImperviousSurfaceRatio: "0",
    commonSpacePercentage: "0",
    parkingRatio: "0",
    catchAll: "0",
    buildingPricePerSqFt: "0",
    hardCostPerSqFt: "0",
    permits: "0",
    miscCosts: "0",
    homeBuilderProfitPercentage: "0",
    realEstateCommissionPercentage: "0",
    landDeveloperProfitPercentage: "0",
    costToDevelop: "0",
    SDCFees: "0",
    ownedLandCost: "0",
    builderProfitPercentage: "0",
    costToDevelopPerLot: "0",
    costToDevelopPerUnit: "0",
    housePricePerSqFt: "0",
    multifamilyPricePerUnit: "0",
    residentialPricePerHome: "0",
    houseSize: "0",
    multifamilyPricePerSqFt: "0",
    numberOfUnits: "0",
    parkingSpotsPerUnit: "0",
    requiresHandicappedParking: true,
    sqFtPerLot: "0",
    unitsPerAcre: "0",
    annualLeaseRatesPerSQFT: "0",
    leasableSQFT: "0",
    percentageOfIncomeToExpenses: "0",
    rents: "0",
    interestRate: "0",
    numberOfYears: "0",
    cashOnCashReturn: "0",
    expensePercentage: "0",
    downPayment: "0",
    buyersAgentFee: "0",
    clostingCostsFee: "0",

    purchasePrice: "0",
    units: "0",
    rentPerUnit: "0",
    repairPerUnit: "0",
    duration: "0",
    taxRate: "0",
    laundryIncome: "0",
    storageIncome: "0",
    parkingIncome: "0",
    otherIncome: "0",
    propertyTax: "0",
    insurance: "0",
    waterSewer: "0",
    garbage: "0",
    electric: "0",
    gas: "0",
    HOAFees: "0",
    lawnSnow: "0",
    vacancy: "0",
    repairs: "0",
    capEx: "0",
    propertyManagement: "0",

    // FOR IRR CALCULATIONS
    originalPurchasePrice: "0",
    originalPurchaseDate: "01-01-1970",
    newPurchasePrice: "0",
    loanOriginationFee: "0",
    loanTerm: "0",
    drawFee: "0",
    underwritingFee: "0",
    inspectionFee: "0",
    appraisalFee: "0",
    titleInsurance: "0",
    recordingFee: "0",
    legalFee: "0",
    interestReserve: "0",
    prepaymentPenalty: "0",
    loanExtensionFee: "0",
    discountPoints: "0",
    propertyValue: "0",
    loanToValue: "0",
    constructionToLongTermLoan: "0",
    isInterestOnly: false,

    arv: "0",
    purchaseAndRepairCosts: "0",
    projectMonths: "0",
    hardMoneyLoanLtv: "0",
    hardMoneyLoanPoints: "0",
    hardMoneyLoanInterestRate: "0",
    gapPoints: "0",
    gapInterestRate: "0",
    hardMoneyLoanAdminFees: "0",
    gapLoanAdminFees: "0",
    closingCosts: "0",

    roof: "0",
    concrete: "0",
    gutters: "0",
    garage: "0",
    siding: "0",
    landscaping: "0",
    exteriorPainting: "0",
    septic: "0",
    decksPorches: "0",
    foundation: "0",
    demo: "0",
    sheetrock: "0",
    plumbing: "0",
    carpentry: "0",
    windows: "0",
    doors: "0",
    electrical: "0",
    interiorPainting: "0",
    hvac: "0",
    cabinets: "0",
    framing: "0",
    flooring: "0",
    insulation: "0",
    termites: "0",
    mold: "0",
    miscellaneous: "0",
    profitPercentage: "0",


    

}
export const DEFAULT_VALUES = {
    [EPageNames.RESIDENTIAL_DEVELOPMENT]: {
        ...DEFAULT_VALUES_ZEROS,
        grossAcres: "1.65",
        unbuildableAcres: "0",
        sqFtPerLot: "1,500",
        unitsPerAcre: "0",
        houseSize: "1,500",
        housePricePerSqFt: "300",
        residentialPricePerHome:"0",
        hardCostPerSqFt: "135",
        permits: "12,000",
        miscCosts: "7,500",
        homeBuilderProfitPercentage: "20",
        realEstateCommissionPercentage: "3",
        landDeveloperProfitPercentage: "15",
        costToDevelopPerLot: "50,000",
        SDCFees: "35,000",
    },
    [EPageNames.MULTIFAMILY_DEVELOPMENT]: {
        ...DEFAULT_VALUES_ZEROS,
        grossAcres: "0.25",
        unbuildableAcres: "0",
        numberOfUnits: "4",
        numberOfFloors: "2",
        maxImperviousSurfaceRatio: "60",
        commonSpacePercentage: "0",
        parkingSpotsPerUnit: "1.5",
        requiresHandicappedParking: true,
        catchAll: "1.8",
        multifamilyPricePerSqFt: "300",
        // multifamilyPricePerUnit:"175,000",
        hardCostPerSqFt: "135",
        permits: "12,000",
        miscCosts: "7,500",
        builderProfitPercentage: "20",
        realEstateCommissionPercentage: "3",
        landDeveloperProfitPercentage: "15",
        costToDevelopPerUnit: "40,000",
    },
    [EPageNames.INDUSTRIAL_DEVELOPMENT]: {
        ...DEFAULT_VALUES_ZEROS,
        grossAcres: "0.3",
        unbuildableAcres: "0",
        numberOfFloors: "2",
        maxImperviousSurfaceRatio: "60",
        commonSpacePercentage: "40",
        parkingRatio: "2",
        catchAll: "1.8",
        buildingPricePerSqFt: "200",
        hardCostPerSqFt: "135",
        permits: "12,000",
        miscCosts: "7,500",
        homeBuilderProfitPercentage: "20",
        realEstateCommissionPercentage: "3",
        landDeveloperProfitPercentage: "15",
        costToDevelop: "40,000",
        SDCFees: "20,000",
        ownedLandCost: "0",
        annualLeaseRatesPerSQFT: "18",
        percentageOfIncomeToExpenses: "45",
    },
    [EPageNames.MULTI_FAMILY_PRICE_PER_DOOR]: {
        ...DEFAULT_VALUES_ZEROS,
        rents: "1,600",
        interestRate: "7.75",
        numberOfYears: "25",
        cashOnCashReturn: "8",
        expensePercentage: "50",
        downPayment: "30",
        units: "4",
        buyersAgentFee:"2.5",
        closingCosts:"1.5"
    },
    [EPageNames.MULTIFAMILY_ANALYSIS]: {
        ...DEFAULT_VALUES_ZEROS,
        purchasePrice: "500,000",
        units: "4",
        rentPerUnit: "1,500",
        repairPerUnit: "0",
        interestRate: "7.75",
        downPayment: "25",
        duration: "25",
        taxRate: "35",
        laundryIncome: "0",
        storageIncome: "0",
        parkingIncome: "0",
        otherIncome: "0",
        propertyTax: "1.65",
        insurance: "2.9",
        waterSewer: "4.4",
        garbage: "4.0",
        electric: "5.3",
        gas: "1",
        HOAFees: "0",
        lawnSnow: "1.15",
        vacancy: "5.0",
        repairs: "3.0",
        capEx: "4.4",
        propertyManagement: "8",

    },
    [EPageNames.IRR_CALCULATOR]: {
        ...DEFAULT_VALUES_ZEROS,
        originalPurchasePrice: "240,000",
        originalPurchaseDate: "2016-04-01",
        newPurchasePrice: "600,000",

    },
    [EPageNames.HARD_MONEY_COST_ESTIMATOR]: {
        ...DEFAULT_VALUES_ZEROS,
        // loanOriginationFee: "1.0",           // 1% of loan amount
        // interestRate: "5.0",                 // 5% annual interest rate
        // loanTerm: "360",                      // 12-month term for short-term loan or construction loan
        // drawFee: "0.25",                     // 0.25% per draw
        // underwritingFee: "0.5",              // 0.5% of loan amount
        // inspectionFee: "300",                // Flat fee per inspection
        // appraisalFee: "500",                 // Flat fee for appraisal
        // titleInsurance: "0.5",               // 0.5% of loan amount
        // recordingFee: "150",                 // Flat recording fee
        // legalFee: "0.75",                    // 0.75% of loan amount for legal fees
        // interestReserve: "10.0",             // 10% of loan amount reserved for interest payments
        // prepaymentPenalty: "2.0",            // 2% of outstanding loan balance if applicable
        // loanExtensionFee: "1.0",             // 1% of loan amount for extension
        // discountPoints: "1.0",               // 1 point equals 1% of loan amount
        // propertyValue: "1,000,000",                // Default property value for loan amount ($)
        // loanToValue: "80",              // Default construction loan percentage (%)
        // constructionToLongTermLoan: "75",    // Default conversion to long-term loan percentage (%)
        // isInterestOnly: false,                  // Default interest-only option (unchecked)

        arv: "400,000",
        purchaseAndRepairCosts: "306,500",
        projectMonths: "9",
        hardMoneyLoanLtv: "70",
        hardMoneyLoanPoints: "1",
        hardMoneyLoanInterestRate: "10",
        gapPoints: "3",
        gapInterestRate: "15",
        hardMoneyLoanAdminFees: "1,000",
        gapLoanAdminFees: "1,000"
    },
    [EPageNames.INDUSTRIAL_PRICE_PER_SQFT]: {
        ...DEFAULT_VALUES_ZEROS,
        annualLeaseRatesPerSQFT: "18",
        leasableSQFT: "5000",
        interestRate: "7.75",
        numberOfYears: "25",
        cashOnCashReturn: "10",
        expensePercentage: "50",
        downPayment: "30",
        units: "4",
        buyersAgentFee:"2.5",
        closingCosts:"1.5",
    },
    [EPageNames.HOUSE_FLIPPING_CALCULATOR]:{
        
        ...DEFAULT_VALUES_ZEROS,
        purchasePrice: "250,000",
        arv: "400,000",
        purchaseAndRepairCosts: "306,500",
        projectMonths: "9",
        hardMoneyLoanLtv: "70",
        hardMoneyLoanPoints: "1",
        hardMoneyLoanInterestRate: "10",
        gapPoints: "3",
        gapInterestRate: "15",
        hardMoneyLoanAdminFees: "1,000",
        gapLoanAdminFees: "1,000",
        realEstateCommissionPercentage: "5",
        profitPercentage:"10",
        closingCosts: "1.5",
        roof: "3000",
        concrete: "10000",
        gutters: "3000",
        garage: "0",
        siding: "10000",
        landscaping: "0",
        exteriorPainting: "2000",
        septic: "3000",
        decksPorches: "4000",
        foundation: "10000",
        demo: "2000",
        sheetrock: "5000",
        plumbing: "3000",
        carpentry: "2000",
        windows: "3000",
        doors: "500",
        electrical: "2000",
        interiorPainting: "2000",
        hvac: "0",
        cabinets: "500",
        framing: "1000",
        flooring: "750",
        insulation: "750",
        permits: "2000",
        termites: "0",
        mold: "1000",
        miscellaneous: "4000",
    },
    [EPageNames.WATERFALL]: {
        ...DEFAULT_VALUES_ZEROS,
    },
    [EPageNames.CONSTRUCTION_BUDGET]: {
        ...DEFAULT_VALUES_ZEROS,
    },
}



export const allStateVariables = [
    EAllStates.builderProfitPercentage,
    EAllStates.buildingPricePerSqFt,
    EAllStates.catchAll,
    EAllStates.commonSpacePercentage,
    EAllStates.costToDevelop,
    EAllStates.costToDevelopPerLot,
    EAllStates.costToDevelopPerUnit,
    EAllStates.grossAcres,
    EAllStates.hardCostPerSqFt,
    EAllStates.homeBuilderProfitPercentage,
    EAllStates.housePricePerSqFt,
    EAllStates.houseSize,
    EAllStates.landDeveloperProfitPercentage,
    EAllStates.maxImperviousSurfaceRatio,
    EAllStates.miscCosts,
    EAllStates.multifamilyPricePerSqFt,
    EAllStates.numberOfFloors,
    EAllStates.numberOfUnits,
    EAllStates.ownedLandCost,
    EAllStates.parkingRatio,
    EAllStates.parkingSpotsPerUnit,
    EAllStates.permits,
    EAllStates.realEstateCommissionPercentage,
    EAllStates.requiresHandicappedParking,
    EAllStates.SDCFees,
    EAllStates.sqFtPerLot,
    EAllStates.unbuildableAcres,
    EAllStates.unitsPerAcre,
]



export enum OutputKeys {
    AdjustedInfrastructure = "adjustedInfrastructure",
    AnnualRentalIncome = "annualRentalIncome",
    BasicLandInfo = "basicLandInfo",
    BuilderProfit = "builderProfit",
    BuildingFootprintArea = "buildingFootprintArea",
    BuildingFootprintDimensions = "buildingFootprintDimensions",
    BuildingSalePrice = "buildingSalePrice",
    CalculatedDrivewayArea = "calculatedDrivewayArea",
    CalculatedImperviousSurfaceRatio = "calculatedImperviousSurfaceRatio",
    CalculatedParkingArea = "calculatedParkingArea",
    CalculatedSidewalkArea = "calculatedSidewalkArea",
    CalculatedValueToLandOwner = "calculatedValueToLandOwner",
    CostToDevelopLand = "costToDevelopLand",
    DrivewayArea = "drivewayArea",
    FinancialAssumptions = "financialAssumptions",
    FinishedLotValue = "finishedLotValue",
    GeneralContractorProfit = "generalContractorProfit",
    HardCostForBuild = "hardCostForBuild",
    HardCostPerSqFt = "hardCostPerSqFt",
    HardCosts = "hardCosts",
    HardCostsTotal = "hardCostsTotal",
    HomeBuilderProfit = "homeBuilderProfit",
    HouseSalePrice = "houseSalePrice",
    ImperviousSurfaceRatio = "imperviousSurfaceRatio",
    LandCosts = "landCosts",
    LandDeveloperProfit = "landDeveloperProfit",
    LandDeveloperProfitPerLot = "landDeveloperProfitPerLot",
    LandPercentage = "landPercentage",
    LandPercentageOfTotalValue = "landPercentageOfTotalValue",
    LandValueIfAlreadyOwned = "landValueIfAlreadyOwned",
    LotSize = "lotSize",
    MiscCosts = "miscCosts",
    MultifamilySalePrice = "multifamilySalePrice",
    NetBuildableAcres = "netBuildableAcres",
    OfferToLandOwner = "offerToLandOwner",
    ParkingArea = "parkingArea",
    Permits = "permits",
    PermitsPerUnit = "PermitsPerUnit",
    ProjectOverview = "projectOverview",
    PropertyCapRate = "propertyCapRate",
    PropertyNOI = "propertyNOI",
    RawLandCalculations = "rawLandCalculations",
    REAgentCommission = "reAgentCommission",
    REAgentCommissionPerUnit = "reAgentCommissionPerUnit",
    SDCFees = "sdcFees",
    SidewalkArea = "sidewalkArea",
    SoftCosts = "softCosts",
    TotalBuildableSqFt = "totalBuildableSqFt",
    TotalBuildingSqft = "totalBuildingSqft",
    TotalCosts = "totalCosts",
    TotalHandicappedParkingSpots = "totalHandicappedParkingSpots",
    TotalHardCosts = "totalHardCosts",
    TotalHardCostsPerUnit = "totalHardCostsPerUnit",
    TotalLeasableSpace = "totalLeasableSpace",
    TotalLotYield = "totalLotYield",
    TotalOfferToLandOwner = "totalOfferToLandOwner",
    TotalParkingSpots = "totalParkingSpots",
    TotalProfit = "totalProfit",
    UnitSqFt = "unitSqFt",
    ValuePerLotToLandOwner = "valuePerLotToLandOwner",

    TotalPermitCosts="permits",
    TotalMiscCosts="miscCosts",
    TotalSDCCosts="costToDevelopPerLot",
    ClosingCosts="totalClosingCosts",
}